# Generated by Django 2.2.7 on 2019-11-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mini_fb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('prof_url', models.TextField(blank=True)),
            ],
        ),
    ]
