# Generated by Django 2.2.7 on 2019-11-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mini_fb',
            name='prof_url',
            field=models.URLField(blank=True),
        ),
    ]
